# docker-compose.yml
version: "3.8"
services:
  grpc-server:
    build:
      context: ./server
    ports:
      - "50051:50051"
    depends_on:
      - db
      - rabbitmq
  db:
    build:
      context: ./db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test
      MYSQL_USER: test
      MYSQL_PASSWORD: test
  rabbitmq:
    build:
      context: ./rabbitmq
    image: rabbitmq:latest
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
    ports:
      - "5672:5672" # RabbitMQ default port
      - "15672:15672" # RabbitMQ management plugin port
  consumer:
    build:
      context: ./consumer
    depends_on:
      - rabbitmq