# Use the official RabbitMQ image from Docker Hub
FROM rabbitmq:latest

# Define environment variables
ENV RABBITMQ_DEFAULT_USER=user
ENV RABBITMQ_DEFAULT_PASS=password

# Expose ports
EXPOSE 5672 15672